package com.example.memoraid.models

import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp
import java.util.*

data class PhotoAlbum(
    @DocumentId val id: String = "", // Automatically generated by Firestore (if not specified)
    val patientId: String = "", // Reference to the Patient ID
    val photos: List<String> = listOf(), // List of photo URLs
    @ServerTimestamp val createdAt: Date? = null // Firestore server timestamp
)
