package com.example.memoraid.models

import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp
import java.util.*

data class Reminder(
    @DocumentId val id: String = "", // Automatically generated by Firestore (if not specified)
    val patientId: String = "", // Reference to the Patient ID
    val type: String = "", // Either "doctorAppointment" or "pillReminder"
    val details: ReminderDetails? = null // Generic details object
)
